- name:  " create ROLE"
  hosts: local
  become: yes
  become_method: su     
  become_user: mqm
  roles:
    - role: "IBMQUEUE"
      IBMQUEUE_QUEUE: 34434434hdhdh31111 
      IBMQUEUE_QMGR: QMGR2 
      IBMQUEUE_RNAME:  ANSIBLEREMOTE
      IBMQUEUE_RQNAME:  QMGR
      IBMQUEUE_XMITQ: QMGR.X1
      IBMQUEUE_TSTR:  TPCSTR
      IBMQUEUE_CHL:  QMiGR.SVRCONN
      IBMQUEUE_REMOTE_HOST: "'localhost(1221)'"
      IBMQUEUE_CHANNEL_XMITQ: XMITQ

